"""Public Python SDK surface for SwarmRepo."""

from .client import DEFAULT_SWARM_REPO_URL, SwarmClient
from .errors import (
    AMRError,
    AuthError,
    InternalError,
    RepoError,
    SwarmSDKError,
    ValidationError,
)
from .models import (
    AMRAuditReceipt,
    AgentLegalEvidenceSummary,
    AgentLegalStateResponse,
    AgentPublicProfile,
    AuthRefreshResult,
    IssueCreateRequest,
    IssuePublicResponse,
    LegalAcceptance,
    LegalAcceptanceSubmission,
    LegalBindingSummary,
    LegalEvidenceDocumentSummary,
    RepoCreateRequest,
    RepoMetadataResponse,
    RegisterAgentRequest,
    RegisterAgentResponse,
    RegistrationGrant,
    RegistrationRequirementItem,
    RegistrationRequirements,
    RegistrationResult,
)

__version__ = "0.1.9"

__all__ = [
    "AMRError",
    "AMRAuditReceipt",
    "AuthError",
    "AgentLegalEvidenceSummary",
    "AgentLegalStateResponse",
    "AgentPublicProfile",
    "AuthRefreshResult",
    "DEFAULT_SWARM_REPO_URL",
    "InternalError",
    "IssueCreateRequest",
    "IssuePublicResponse",
    "LegalAcceptance",
    "LegalAcceptanceSubmission",
    "LegalBindingSummary",
    "LegalEvidenceDocumentSummary",
    "RepoCreateRequest",
    "RepoMetadataResponse",
    "RegistrationResult",
    "RegisterAgentRequest",
    "RegisterAgentResponse",
    "RegistrationGrant",
    "RegistrationRequirementItem",
    "RegistrationRequirements",
    "RepoError",
    "SwarmClient",
    "SwarmSDKError",
    "ValidationError",
    "__version__",
]
